### ISSUE TITLE
use easyrefresh with TabBar and TabBarView has exception

### ISSUE THREAD

**Issue by fuyong859050943** [xuelongqy/flutter_easyrefresh#165]
* easyrefresh version 2.0.4
* Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
* Framework • revision 20e59316b8 (9 weeks ago) • 2019-07-18 20:04:33 -0700
* Engine • revision fee001c93f
* Tools • Dart 2.4.0

the tab page has `TabBar` and `TabBarView`,  every tab page has easyrefresh
```dart
 class MyDemo extends StatelessWidget {
   final List<Tab> myTabs = <Tab>[
     Tab(text: 'LEFT'),
     Tab(text: 'RIGHT'),
   ];

   @override
   Widget build(BuildContext context) {
     return DefaultTabController(
       length: myTabs.length,
       child: Scaffold(
         appBar: AppBar(
           bottom: TabBar(
             tabs: myTabs,
           ),
         ),
         body: TabBarView(
           children: myTabs.map((Tab tab) {
             final String label = tab.text.toLowerCase();
             return Center(
               child: Text(
                 'This is the $label tab',
                 style: const TextStyle(fontSize: 36),
               ),
             );
           }).toList(),
         ),
       ),
     );
   }
 }
```
tab page maybe like this 
```dart
class OrderPage extends StatefulWidget {
  final int status;

  OrderPage({this.status, Key key}) : super(key: key);

  _OrderPageState createState() => _OrderPageState();
}

class _OrderPageState extends State<OrderPage>
    with AutomaticKeepAliveClientMixin {
  /// 订单列表是否还有更多
  bool _isLoadMore = true;
  bool _isFirstLoad = true;

  /// 订单列表当前页
  int _pageNumber = 1;

  /// 订单列表数据
  List<OrderModel> _orderItems = [];

  GlobalKey _easyRefreshKey = new GlobalKey();

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    super.build(context);
    return Scaffold(
      body: Center(
        child: new EasyRefresh(
          key: _easyRefreshKey,
          emptyWidget:
              !_isFirstLoad && (_orderItems == null || _orderItems.length <= 0)
                  ? WidgetNoData()
                  : null,
          firstRefresh: true,
          firstRefreshWidget: WidgetFirstRefresh(),
          child: ListView.builder(
            itemCount: _orderItems?.length ?? 0,
            itemBuilder: (context, index) => OrderItem(
              _orderItems[index],
            ),
            padding: EdgeInsets.only(bottom: 15.0),
          ),
          onRefresh: () async {
            _pageNumber = 1;
            _apiGetMeOrders();
          },
          onLoad: _isLoadMore
              ? () async {
                  if (_isLoadMore) {
                    _pageNumber++;
                    await new Future(_apiGetMeOrders);
                  } else {
                    setState(() {});
                  }
                }
              : null,
        ),
      ),
    );
  }

  /// 获取订单分页数据
  void _apiGetMeOrders() async {
    await OrderApi.getOrderPage(pageNumber: _pageNumber, status: widget.status)
        .then((val) {
      var items = val.data.records;
      var page = val.data;
      // 判断是否有下一页(当前页码 * 每页行数 < 总行数)
      _isLoadMore = (page.current * page.size) < page.total;
      setState(() {
        if (_pageNumber == 1) {
          _orderItems.clear();
        }
        _orderItems.addAll(items);
        _isFirstLoad = false;
      });
    });
  }

  @override
  bool get wantKeepAlive => true;
}
```
when click tab index 0, next click tab index 2, then will throw an exception when EasyRefresh firstRefresh is true. exception like this
```dart
I/flutter ( 3684): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 3684): The following NoSuchMethodError was thrown during a scheduler callback:
I/flutter ( 3684): The method 'inheritFromWidgetOfExactType' was called on null.
I/flutter ( 3684): Receiver: null
I/flutter ( 3684): Tried calling: inheritFromWidgetOfExactType(PrimaryScrollController)
I/flutter ( 3684): 
I/flutter ( 3684): When the exception was thrown, this was the stack:
I/flutter ( 3684): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
I/flutter ( 3684): #1      PrimaryScrollController.of (package:flutter/src/widgets/primary_scroll_controller.dart:49:52)
I/flutter ( 3684): #2      _EasyRefreshState._scrollerController (package:flutter_easyrefresh/src/refresher.dart:232:33)
I/flutter ( 3684): #3      _EasyRefreshState.callRefresh (package:flutter_easyrefresh/src/refresher.dart:297:9)
I/flutter ( 3684): #4      _EasyRefreshState.initState.<anonymous closure> (package:flutter_easyrefresh/src/refresher.dart:266:9)
I/flutter ( 3684): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
I/flutter ( 3684): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:966:9)
I/flutter ( 3684): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
I/flutter ( 3684): #11     _invoke (dart:ui/hooks.dart:236:10)
I/flutter ( 3684): #12     _drawFrame (dart:ui/hooks.dart:194:3)
I/flutter ( 3684): (elided 3 frames from package dart:async)
I/flutter ( 3684): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 3684): Another exception was thrown: NoSuchMethodError: The method 'inheritFromWidgetOfExactType' was called on null.
```
I have read the `TabBarView` source, the problem is `TabBarView` will preload the previous tab page. and the context is null. EasyRefresh didn't resolve this problem

**Comment by xuelongqy** [comment]
Add ScrollController and try it out？

**Comment by fuyong859050943** [comment]
it's worked, thank you

**Comment by jahnli** [comment]
哪一部分添加ScrollController  @xuelongqy  @fuyong859050943
