### ISSUE TITLE
更新android studio和flutter版本后，加载flare动画报错

### ISSUE THREAD

**Issue by taoyimin** [xuelongqy/flutter_easyrefresh#245]
```
E/flutter (15398): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Unable to load asset: assets/flare/Space Demo.flr
E/flutter (15398): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
E/flutter (15398): <asynchronous suspension>
E/flutter (15398): #1      FlareCacheAsset.load (package:flare_flutter/flare_cache_asset.dart:18:20)
E/flutter (15398): #2      Cache.getAsset (package:flare_flutter/cache.dart:55:15)
E/flutter (15398): #3      cachedActor (package:flare_flutter/flare_cache.dart:35:16)
E/flutter (15398): #4      FlareRenderBox.loadFlare (package:flare_flutter/flare_render_box.dart:268:35)
E/flutter (15398): #5      FlareActorRenderObject.load (package:flare_flutter/flare_actor.dart:222:5)
E/flutter (15398): #6      FlareActorRenderObject.filename= (package:flare_flutter/flare_actor.dart:213:5)
E/flutter (15398): #7      FlareActor.createRenderObject (package:flare_flutter/flare_actor.dart:45:9)
E/flutter (15398): #8      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5052:28)
E/flutter (15398): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (15398): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (15398): #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (15398): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (15398): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (15398): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (15398): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (15398): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (15398): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (15398): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (15398): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (15398): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (15398): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (15398): #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (15398): #23     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter (15398): #24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (15398): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (15398): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (15398): #27     _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:115:18)
E/flutter (15398): #28     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2412:19)
E/flutter (15398): #29     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:95:11)
E/flutter (15398): #30     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1823:58)
E/flutter (15398): #31     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:875:15)
E/flutter (15398): #32     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1823:13)
E/flutter (15398): #33     RenderConstrainedLayoutBuilder.layoutAndBuildChild (package:flutter/src/widgets/layout_builder.dart:173:5)
E/flutter (15398): #34     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:240:5)
E/flutter (15398): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (15398): #36     _RenderEasyRefreshSliverRefresh.performLayout (package:flutter_easyrefresh/src/header/refresh_indicator.dart:252:13)
E/flutter (15398): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (15398): #38     _RenderEasyRefreshSliverRefresh.layout (package:flutter_easyrefresh/src/header/refresh_indicator.dart:177:13)
E/flutter (15398): #39     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:410:13)
E/flutter (15398): #40     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1367:12)
E/flutter (15398): #41     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1285:20)
E/flutter (15398): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (15398): #43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_b
```
<br/>

```
flutter doctor
```
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.356], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)

• No issues found!
```
<br/>

```
pubspec.yaml
```
```
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/flare/Space Demo.flr
    - assets/images/
```

**Comment by taoyimin** [comment]
执行flutter clean命令后，重新运行仍然存在该问题。

**Comment by xuelongqy** [comment]
这应该是flare版本更新的问题，请使用flare最新的api

**Comment by xuelongqy** [comment]
将空格去掉，请参考示例
