### ISSUE TITLE
多个标签页快速切换会报异常

### ISSUE THREAD

**Issue by fanqi** [xuelongqy/flutter_easyrefresh#287]
多个标签页快速切换会报以下exception：
```
════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during a scheduler callback:
The method 'dependOnInheritedWidgetOfExactType' was called on null.
Receiver: null
Tried calling: dependOnInheritedWidgetOfExactType<PrimaryScrollController>()

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      PrimaryScrollController.of (package:flutter/src/widgets/primary_scroll_controller.dart:49:52)
#2      _EasyRefreshState._scrollerController (package:flutter_easyrefresh/src/refresher.dart:241:33)
#3      _EasyRefreshState.callRefresh (package:flutter_easyrefresh/src/refresher.dart:306:9)
#4      _EasyRefreshState.initState.<anonymous closure> (package:flutter_easyrefresh/src/refresher.dart:275:9)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by xuelongqy** [comment]
我觉得设置不同的ScrollController应该可以解决问题
