### ISSUE TITLE
使用TabBarView时,切换间隔1个以上的 tab 时报错

### ISSUE THREAD

**Issue by chinachen01** [xuelongqy/flutter_easyrefresh#293]
```dart
  static List<Widget> _orderList = [_ListPage(OrderStatus.TO_BE_RECEIVED),
    _ListPage(OrderStatus.TO_BE_DELIVERED),
    _ListPage(OrderStatus.ALREADY_DELIVERED),
    _ListPage(OrderStatus.ALL)];

   List<Widget> _tabs = _buildTabs(['待接单', '待发货', '已发货', '近三个月']);
    Widget build(BuildContext context) {
       return TabBarView(
                  controller: _tabController,
                  children: _orderList,
                );
   }
```
比如我当前处于待接单这个 tab，直接点击已发货 tab，此时会报以下错误。
PS: 我设置了 firstRefresh 属性为 true
```
════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during a scheduler callback:
The method 'dependOnInheritedWidgetOfExactType' was called on null.
Receiver: null
Tried calling: dependOnInheritedWidgetOfExactType<PrimaryScrollController>()

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      PrimaryScrollController.of (package:flutter/src/widgets/primary_scroll_controller.dart:49:52)
#2      _EasyRefreshState._scrollerController (package:flutter_easyrefresh/src/refresher.dart:241:33)
#3      _EasyRefreshState.callRefresh (package:flutter_easyrefresh/src/refresher.dart:306:9)
#4      _EasyRefreshState.initState.<anonymous closure> (package:flutter_easyrefresh/src/refresher.dart:275:9)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by scheduler library ═════════════════════════════════════════════════
The method 'dependOnInheritedWidgetOfExactType' was called on null.
Receiver: null
Tried calling: dependOnInheritedWidgetOfExactType<PrimaryScrollController>()
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by xuelongqy** [comment]
设置不同的ScrollController，如果有需要，可以设置tab页保活
