### ISSUE TITLE
在Sliver中加载更多报错

### ISSUE THREAD

**Issue by Gennki** [xuelongqy/flutter_easyrefresh#4]
错误日志如下
```
E/flutter (28676): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (28676): NoSuchMethodError: The method '>' was called on null.
E/flutter (28676): Receiver: null
E/flutter (28676): Tried calling: >(null)
E/flutter (28676): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter (28676): #1      EasyRefreshState._checkStateAndCallback (package:flutter_easyrefresh/src/refresher.dart:704:47)
E/flutter (28676): #2      EasyRefreshState._refreshStart (package:flutter_easyrefresh/src/refresher.dart:382:5)
E/flutter (28676): <asynchronous suspension>
E/flutter (28676): #3      EasyRefreshState.initState.<anonymous closure>.<anonymous closure> (package:flutter_easyrefresh/src/refresher.dart:256:13)
E/flutter (28676): #4      State.setState (package:flutter/src/widgets/framework.dart:1130:30)
E/flutter (28676): #5      EasyRefreshState.initState.<anonymous closure> (package:flutter_easyrefresh/src/refresher.dart:250:9)
E/flutter (28676): #6      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin&AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:188:19)
E/flutter (28676): #7      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:682:7)
E/flutter (28676): #8      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:698:5)
E/flutter (28676): #9      Ticker._tick (package:flutter/src/scheduler/ticker.dart:228:5)
E/flutter (28676): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
E/flutter (28676): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:906:11)
E/flutter (28676): #12     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
E/flutter (28676): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:904:17)
E/flutter (28676): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:834:5)
```

**Comment by Gennki** [comment]
这个效果真的很棒,很期待能够支持Sliver系列

**Comment by xuelongqy** [comment]
有示例吗？

**Comment by Gennki** [comment]
这是我的示例:

```dart
  @override
  Widget build(BuildContext context) {
      
    return Scaffold(
        body: EasyRefresh(
      key: _refreshKey,
      refreshHeader: MaterialHeader(
        key: _headerKey,
      ),
      refreshFooter: BallPulseFooter(
        key: _footerKey,
      ),
      onRefresh: () {
        _bloc.refresh();
      },
      loadMore: () async {
        _bloc.loadMore();
      },
      autoLoad: true,
      child: CustomScrollView(
        slivers: <Widget>[
          MarketSliverAppBar(),// 这是个SliverAppBar
          MarketSliverGlideView(),// 这是个SliverGrid
          MarketSliverListView()// 这是个SliverList
        ],
      ),
    ));
  }
}
```

**Comment by xuelongqy** [comment]
已经找到问题，CustomScrollView没有同步semanticChildCount，这可能是flutter的bug。但有另外的解决办法，将会在下一次更新提交。你可以加QQ进行讨论

**Comment by xuelongqy** [comment]
V1.0.3已解决，请参考[sliver_page.dart](https://github.com/xuelongqy/flutter_easyrefresh/blob/master/example/lib/page/sliver_page.dart)
