### ISSUE TITLE
禁止加载后报错

### ISSUE THREAD

**Issue by zhangyingcheng** [xuelongqy/flutter_easyrefresh#401]
当加载完成，禁止加载后再次刷新就会报错，

```
setState() called after dispose(): _EasyRefreshSliverLoadControlState#73477(lifecycle state: defunct, not mounted)

This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.

The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

When the exception was thrown, this was the stack: 
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1208:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1243:6)
#2      _EasyRefreshSliverLoadControlState.initState.<anonymous closure> (package:flutter_easyrefresh/src/footer/load_indicator.dart:618:9)
#3      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:226:25)
#4      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:292:5)
```

**Comment by xuelongqy** [comment]
v2.1.7已修复
