### ISSUE TITLE
v2.2.1 使用TabBarView切换页面，页面使用firstRefresh: true会出现Null check operator used on a null value

### ISSUE THREAD

**Issue by liziliang123** [xuelongqy/flutter_easyrefresh#509]

**Comment by 1244752609** [comment]
我也出现，Android没问题，ios有问题

**Comment by RA1NO3O** [comment]
EasyRefreshController似乎在翻页后被销毁了。
```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: A ValueNotifier<TaskState> was used after being disposed.
Once you have called dispose() on a ValueNotifier<TaskState>, it can no longer be used.
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:114:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:120:6)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:288:12)
#3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:412:5)
#4      _EasyRefreshSliverRefreshControlState.finishRefresh (package:flutter_easyrefresh/src/header/refresh_indicator.dart:643:25)
#5      EasyRefreshController.finishRefresh (package:flutter_easyrefresh/src/refresher.dart:640:29)
#6      _StudyStatisticsPageState._grantDataList (package:pocket_prep_app/page_gen2/home/study_statistics_page.dart:451:26)
<asynchronous suspension>
```
位于study_statistics_page.dart line451:26的代码：
` _refreshCtrl.finishRefresh();`

**Comment by RA1NO3O** [comment]
> No description provided.

检查一下TabBar的点击事件中是否调用了EasyRefreshController的finishRefresh方法。

**Comment by xuelongqy** [comment]
v3已发布，也许问题得到解决。如果问题依然存在，请重新打开
