### ISSUE TITLE
Unhandled Exception: LateInitializationError: Field '_position@86089737' has not been initialized.

### ISSUE THREAD

**Issue by xyhuangjia** [xuelongqy/flutter_easyrefresh#576]
使用代码
```
class CollectionView extends StatefulWidget {
  ······
  ······
}

class _CollectionViewState extends State<CollectionView> {
  List<String> tabNames = [];
  List<String> cllxs = [];
  int tabIndex = 0;

  @override
  void initState() {
    super.initState();

    tabNames = ["x x", "xx", "xx", "xx"];
    cllxs = ["xx", "xx", "xx", "xx"];
  }

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
        length: tabNames.length,
        child: Scaffold(
          appBar: AppBar(
            leading: IconButton(
              icon: const Icon(Icons.arrow_back),
              onPressed: () {
                Tool.goBackAction(context);
              },
            ),
            automaticallyImplyLeading: true,
            title: Text(widget.title),
            centerTitle: true,
          ),
          body: Column(
            children: [
              Container(
                color: Colors.white,
                alignment: Alignment.center,
                child: TabBar(
                  onTap: (value) {
                    setState(() {
                      tabIndex = value;
                    });
                  },
                  unselectedLabelColor: const Color.fromRGBO(102, 102, 102, 1),
                  labelColor: const Color.fromRGBO(71, 129, 255, 1),
                  indicatorColor: const Color.fromRGBO(71, 129, 255, 1),
                  indicatorSize: TabBarIndicatorSize.label,
                  tabs: tabNames.map((f) {
                    return Tab(
                      text: f,
                      height: 30.h,
                    );
                  }).toList(),
                ),
              ),
              Expanded(
                child: TabBarView(
                  children: tabNames.asMap().keys.map((index) {
                    return NeedMeSubView(
                      czlx: widget.czlx,
                      hclx: cllxs[index],
                    );
                  }).toList(),
                ),
              ),
            ],
          ),
        ));
  }
}

/// 子视图
class NeedMeSubView extends StatefulWidget {
  final String? czlx;
  final String? hclx;

  const NeedMeSubView({Key? key, this.czlx, this.hclx}) : super(key: key);

  @override
  _NeedMeSubViewState createState() => _NeedMeSubViewState();
}

class _NeedMeSubViewState extends State<NeedMeSubView>
    with AutomaticKeepAliveClientMixin {
  int pageNum = 1;
  int pageSize = 10;
  String keywords = "";
  List<BusinessData> dataList = [];
  StreamSubscription<EventBusSearchData>? searchBusFn;
  StreamSubscription<EventListReloadData>? reloadBusFn;

  @override
  void dispose() {
    super.dispose();
    //取消订阅
    searchBusFn?.cancel();
    reloadBusFn?.cancel();
  }

  @override
  void initState() {
    super.initState();
    loadData();
    searchBusFn = eventBus.on<EventBusSearchData>().listen((event) {
      keywords = event.keyWords ?? "";
      _controller.callRefresh();
    });
    reloadBusFn = eventBus.on<EventListReloadData>().listen((event) {
      _controller.callRefresh();
    });
  }

  final Map<String, String> _typeNameMap = {};
  final Map<String, String> _levelNameMap = {};
  final Map<String, String> _sourceNameMap = {};
  final Map<String, String> _tagNameMap = {};
  EasyRefreshController _controller = EasyRefreshController(
    controlFinishRefresh: true,
    controlFinishLoad: true,
  );

  /// 下载数据接口
  void loadData() {
    Future.wait([
      loadSubData("QQ", "QQ"),
      loadSubData("ZL", "ZL"),
      loadSubData("HC", "ZB"),
    ]).then((value) {
      _controller.callRefresh();
    });
  }

  Future<void> loadSubData(String type, String hclx) async {
   
    /// 接口服务
  }

  /// 刷新数据
  void _onRefresh() async {
    pageNum = 1;
    FCNetService.queryCollectList({
          "keywords": keywords,
          "pageNum": 1,
          "pageSize": 10,
          "czlx": widget.czlx,
          "hclx": widget.hclx,
        }, (v) {
      if (mounted) {
        setState(() {
          DataResult<BusinessDataList> dataResult = DataResult.fromJson(
              v,
              (value) =>
                  BusinessDataList.fromJson(value as Map<String, dynamic>));
          if (dataResult.code == 200) {
           
            dataList.addAll(dataResult.data?.list ?? []);
               _controller.finishRefresh();
              _controller.resetFooter();
          } else {
            BrnToast.show(
              dataResult.message ?? "",
              context,
              gravity: BrnToastGravity.bottom,
            );
            _controller.finishRefresh();
            _controller.resetFooter();
          }
        });
      }
    }, (p0) { });
   
  }

  void _onLoading() async {
    pageNum++;
    FCNetService.queryCollectList({
      "keywords": keywords,
      "pageNum": pageNum,
      "pageSize": pageSize,
      "czlx": widget.czlx,
      "hclx": widget.hclx,
    }, (v) {
      if (mounted) {
        setState(() {
          DataResult<BusinessDataList> dataResult = DataResult.fromJson(
              v,
                  (value) =>
                  BusinessDataList.fromJson(value as Map<String, dynamic>));
          if (dataResult.code == 200) {
            List<BusinessData> list = [];
          
            list.addAll(dataResult.data?.list ?? []);
            if (list.isEmpty) {
              // _refreshController.loadNoData();
              _controller.finishLoad(IndicatorResult.noMore);
            } else {
              dataList.addAll(list);
              // _refreshController.loadComplete();
              _controller.finishLoad(IndicatorResult.success);
            }
          } else {
            // _refreshController.loadComplete();
            _controller.finishLoad(IndicatorResult.success);
            BrnToast.show(
              dataResult.message ?? "",
              context,
              gravity: BrnToastGravity.bottom,
            );
          }
        });
      }
    }, (e) { });

  }

  @override
  Widget build(BuildContext context) {
    super.build(context);
    return EasyRefresh(
        // enablePullDown: true,
        // enablePullUp: true,
        controller: _controller,
        onRefresh: _onRefresh,
        onLoad: _onLoading,
        child: dataList.isEmpty
            ? const ZAEmptyView()
            : ListView.separated(
                itemBuilder: (BuildContext context, int index) => InkWell(
                      child: CollectionCardView(
                        data: dataList[index],
                        hclx: widget.hclx,
                        czlx: widget.czlx,
                      ),
                      onTap: () {
                      
                      },
                    ),
                separatorBuilder: (BuildContext context, int index) =>
                    const Divider(
                      height: 1,
                      color: ColorUtil.separatLineColor,
                    ),
                itemCount: dataList.length));
  }

  @override
  bool get wantKeepAlive => true;
}
```
异常信息
```
E/flutter ( 4060): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: LateInitializationError: Field '_position@86089737' has not been initialized.
E/flutter ( 4060): #0      IndicatorNotifier._position (package:easy_refresh/src/notifier/indicator_notifier.dart)
E/flutter ( 4060): #1      HeaderNotifier.animateToOffset (package:easy_refresh/src/notifier/indicator_notifier.dart:879:8)
E/flutter ( 4060): #2      IndicatorNotifier.callTask (package:easy_refresh/src/notifier/indicator_notifier.dart:375:12)
E/flutter ( 4060): #3      _EasyRefreshState._callRefresh (package:easy_refresh/src/easy_refresh.dart:417:28)
E/flutter ( 4060): #4      EasyRefreshController.callRefresh (package:easy_refresh/src/controller/controller.dart:36:19)
E/flutter ( 4060): #5      _NeedMeSubViewState.loadSubData.<anonymous closure> (package:hczz/pages/mine/view/collection_view.dart:282:19)
E/flutter ( 4060): #6      _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter ( 4060): #7      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 4060): <asynchronous suspension>
```
系统版本
```
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-arm, locale
    zh-Hans-CN)
    • Flutter version 3.0.4 at /opt/homebrew/Caskroom/flutter/3.0.4/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (4 weeks ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huangj/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • KOZ AL40 (mobile) • A7JC9X1A09G11375 • android-arm64  • Android 10 (API
      29)
    • macOS (desktop)   • macos            • darwin-arm64   • macOS 12.4 21F79
      darwin-arm
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Comment by xyhuangjia** [comment]
排查代码后发现问题可能出在这里
```
dataList.isEmpty
            ? const ZAEmptyView()
            : ListView.separated(
                itemBuilder: (BuildContext context, int index) => InkWell(
                      child: CollectionCardView(
                        data: dataList[index],
                        hclx: widget.hclx,
                        czlx: widget.czlx,
                      ),
                      onTap: () {
                      
                      },
                    ),
                separatorBuilder: (BuildContext context, int index) =>
                    const Divider(
                      height: 1,
                      color: ColorUtil.separatLineColor,
                    ),
                itemCount: dataList.length));
```

**Comment by xyhuangjia** [comment]
> 排查代码后发现问题可能出在这里
> 
> ```
> dataList.isEmpty
>             ? const ZAEmptyView()
>             : ListView.separated(
>                 itemBuilder: (BuildContext context, int index) => InkWell(
>                       child: CollectionCardView(
>                         data: dataList[index],
>                         hclx: widget.hclx,
>                         czlx: widget.czlx,
>                       ),
>                       onTap: () {
>                       
>                       },
>                     ),
>                 separatorBuilder: (BuildContext context, int index) =>
>                     const Divider(
>                       height: 1,
>                       color: ColorUtil.separatLineColor,
>                     ),
>                 itemCount: dataList.length));
> ```

排查后发现是占位图设置的问题,现在如何设置空页面占位图？ @xuelongqy

**Comment by xuelongqy** [comment]
空视图放在itemBuilder里面判断
