### ISSUE TITLE
Cannot use ListView within item in scrollable list

### ISSUE THREAD

**Issue by habibrosyad** [xuelongqy/flutter_easyrefresh#591]
Hi,

I found that your package is quite easy to works with except for one use case. In our app, we have a list of scrollable items (in a ListView), and each item has a horizontal scrolling ListView containing chips (displaying tags for the item). Something like this (just for example):

<img width="234" alt="image" src="https://user-images.githubusercontent.com/4804060/183531170-a1db32e8-5f6d-4197-8da8-da12fa8bcc97.png">

I try to reproduce this issue in the example app by modifying the SkeletonItem widget (lib/widget/skeleton_item.dart) adding ListView into the structure:

```dart
import 'package:flutter/material.dart';

/// Skeleton list item.
class SkeletonItem extends StatelessWidget {
  /// Scrollable direction.
  final Axis direction;

  const SkeletonItem({
    Key? key,
    this.direction = Axis.vertical,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final themeData = Theme.of(context);
    final backgroundColor = themeData.colorScheme.surfaceVariant;
    final foregroundColor = themeData.colorScheme.surface;
    if (direction == Axis.vertical) {
      return Card(
        elevation: 0,
        color: backgroundColor,
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Container(
                margin: const EdgeInsets.only(right: 16),
                height: 80,
                width: 80,
                color: foregroundColor,
              ),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Container(
                      margin: const EdgeInsets.only(top: 8, right: 24),
                      height: 12,
                      width: double.infinity,
                      constraints: const BoxConstraints(
                        maxWidth: 200,
                      ),
                      color: foregroundColor,
                    ),
                    Container(
                      margin: const EdgeInsets.only(top: 16),
                      height: 12,
                      width: 80,
                      color: foregroundColor,
                    ),
                    ListView(
                      scrollDirection: Axis.horizontal,
                      children:
                          List.generate(5, (index) => Text('test $index')),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      );
    }
    return Card(
      elevation: 0,
      color: backgroundColor,
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Container(
              margin: const EdgeInsets.only(bottom: 16),
              height: 80,
              width: 80,
              color: foregroundColor,
            ),
            Expanded(
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Container(
                    margin: const EdgeInsets.only(left: 8, bottom: 24),
                    width: 12,
                    height: double.infinity,
                    constraints: const BoxConstraints(
                      maxHeight: 200,
                    ),
                    color: foregroundColor,
                  ),
                  Container(
                    margin: const EdgeInsets.only(left: 16),
                    width: 12,
                    height: 80,
                    color: foregroundColor,
                  ),
                  Container(
                    margin: const EdgeInsets.only(left: 8),
                    width: 12,
                    height: 80,
                    color: foregroundColor,
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

The relevant line for tests would be:
```dart
ListView(
 scrollDirection: Axis.horizontal,
  children:
      List.generate(5, (index) => Text('test $index')),
),
```
Here is the error logs:
```
The relevant error-causing widget was:
  ListView
  ListView:file:///Users/kkt3/sandbox/flutter_easy_refresh/example/lib/widget/skeleton_item.dart:52:21

When the exception was thrown, this was the stack:
#0      RenderViewport.computeDryLayout.<anonymous closure> (package:flutter/src/rendering/viewport.dart:1375:15)
#1      RenderViewport.computeDryLayout (package:flutter/src/rendering/viewport.dart:1436:6)
#2      RenderBox.performResize (package:flutter/src/rendering/box.dart:2381:12)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:1894:9)
#4      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#7      RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#9      RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#11     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#13     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#14     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#15     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#16     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#17     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:829:43)
#18     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931:32)
#19     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#20     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#21     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:896:45)
#22     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931:32)
#23     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#24     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:233:12)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#27     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#29     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#31     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#34     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#36     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:233:12)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#41     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#44     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:213:28)
#45     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#46     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#47     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580:12)
#48     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489:20)
#49     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#50     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#51     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#53     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#55     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#57     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#59     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#61     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#62     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#63     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#64     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#65     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#66     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#67     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#68     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:240:19)
#69     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#70     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
#71     _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:167:11)
#72     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#73     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#74     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580:12)
#75     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489:20)
#76     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#78     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#79     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#80     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#81     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#82     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#83     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#84     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#85     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#86     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#87     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#88     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#89     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#90     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:896:45)
#91     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931:32)
#92     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#93     RenderSliverFillRemainingWithScrollable.performLayout (package:flutter/src/rendering/sliver_fill.dart:92:14)
#94     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#95     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#96     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580:12)
#97     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489:20)
#98     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#99     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#100    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#101    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#102    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#103    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#104    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#105    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#106    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#107    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#108    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#109    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#110    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#111    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#112    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1003:7)
#113    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#114    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#115    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#116    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#117    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#118    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#119    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
#120    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#121    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#122    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#123    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#124    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#125    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#126    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#127    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#128    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#129    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#130    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#131    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#132    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#133    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#134    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#135    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#136    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#137    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#138    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#139    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#140    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#141    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#142    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#143    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#144    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#145    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#146    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#147    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#148    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#149    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#150    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#151    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#152    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#153    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3460:14)
#154    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#155    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#156    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#157    _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:749:15)
#158    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1757:7)
#159    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
#160    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:504:19)
#161    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892:13)
#162    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#163    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#164    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#165    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#169    _invoke (dart:ui/hooks.dart:151:10)
#170    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#171    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)

The following RenderObject was being processed when the exception was fired: RenderViewport#833be NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
  needs compositing
  creator: Viewport ← IgnorePointer-[GlobalKey#9d936] ← Semantics ← Listener ← _GestureSemantics ←
    RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#5fb03] ← Listener ← _ScrollableScope
    ← _ScrollSemantics-[GlobalKey#83f3e] ← NotificationListener<ScrollMetricsNotification> ←
    Scrollable ← ListView ← ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=224.0, 0.0<=h<=Infinity)
  size: MISSING
  axisDirection: down
  crossAxisDirection: right
  offset: ScrollPositionWithSingleContext#a4513(offset: 0.0, range: null..null, viewport: null,
    ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics ->
    RangeMaintainingScrollPhysics, IdleScrollActivity#03949, ScrollDirection.idle)
  anchor: 0.0
This RenderObject had the following descendants (showing up to depth 5):
    center child: RenderSliverPadding#196ee NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child: RenderSliverList#e72cd NEEDS-LAYOUT NEEDS-PAINT
```

I use the TabBarView example. But, checking on the other pages which use SkeletonItem result in the same behavior.

**Comment by xuelongqy** [comment]
readme
