### ISSUE TITLE
连续多次下拉header动画会卡住控制台报错

### ISSUE THREAD

**Issue by THJLearn** [xuelongqy/flutter_easyrefresh#745]
![image](https://github.com/xuelongqy/flutter_easy_refresh/assets/12946242/55ede80d-1d73-4660-b54d-17b760f65a35)
![image](https://github.com/xuelongqy/flutter_easy_refresh/assets/12946242/9278c9f8-f848-41c0-b49b-5e7ebe708ee1)

flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1145 pos 20:
object.dart:1145
flutter: 'node.isRepaintBoundary': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=2_bug.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      PipelineOwner.flushPaint
object.dart:1145
flutter: #3      RendererBinding.drawFrame
binding.dart:494
flutter: #4      WidgetsBinding.drawFrame
binding.dart:905
flutter: #5      RendererBinding._handlePersistentFrameCallback
binding.dart:358
flutter: #6      SchedulerBinding._invokeFrameCallback
binding.dart:1284
flutter: #7      SchedulerBinding.handleDrawFrame
binding.dart:1214
flutter: #8      SchedulerBinding._handleDrawFrame
binding.dart:1072
flutter: #12     _invoke (dart:ui/hooks.dart:144:10)
flutter: #13     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
flutter: #14     _drawFrame (dart:ui/hooks.dart:112:31)
flutter: (elided 5 frames from class _AssertionError and dart:async)

flutter版本号
Flutter 3.10.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 682aa387cf (8 weeks ago) • 2023-06-05 18:04:56 -0500
Engine • revision 2a3401c9bb
Tools • Dart 3.0.3 • DevTools 2.23.1

Xcode  14.2
Simulator iPhone X 16.2

code：

Widget builder = EasyRefresh(
      controller: controller,
      header: widget.header ?? _defaultHeader,
      footer: widget.footer ?? _defaultFooter,
      onRefresh: onRefresh,
      onLoad: widget.onLoadMore != null ? onLoadMore : null,
      child: child,
    );

final controller = EasyRefreshController(
    controlFinishRefresh: true,
    controlFinishLoad: true,
  );
  int pageSize = 1;
  bool firstRenderBuilder = false;
  dynamic prevData;

  Future onRefresh() async {
    controller.callRefresh();
    pageSize = 1;
    widget.onRefresh(pageSize);
    controller
      ..finishRefresh()
      ..resetFooter();
  }

下载demo试了试也有同样的问题
![image](https://github.com/xuelongqy/flutter_easy_refresh/assets/12946242/915b1d22-d26b-4d63-a1e4-c77be25802e1)

**Comment by THJLearn** [comment]
easy_refresh:
    dependency: transitive
    description:
      name: easy_refresh
      sha256: "77b025ea49f27b5ebc5eef40a6678be52564c293bd97ce91a4088d6646478329"
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "3.3.2+1"

**Comment by liamleeq** [comment]
me too

**Comment by fanfq** [comment]
header: const CupertinoHeader() 必复现

**Comment by zhangdc** [comment]
+1

**Comment by onlyYU** [comment]
+10086

**Comment by fallenleavesguy** [comment]
+1
下拉刷新动画正在回去时，拼命滑下面的内容，会报错

**Comment by Luvain9** [comment]
Same problem here !

**Comment by lixp185** [comment]
+1。还没解决吗

**Comment by Gofive** [comment]
作者没有看到这个issue吗

**Comment by lixp185** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
