### ISSUE TITLE
tab_bar_view_page 示例滑动偶现 Exception 的问题

### ISSUE THREAD

**Issue by zhuscat** [xuelongqy/flutter_easyrefresh#826]
报错如下：
```
════════ Exception caught by animation library ═════════════════════════════════
The following assertion was thrown while notifying listeners for AnimationController:
'package:flutter/src/widgets/nested_scroll_view.dart': Failed assertion: line 1588 pos 12: 'result': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      _NestedOuterBallisticScrollActivity.applyMoveTo (package:flutter/src/widgets/nested_scroll_view.dart:1588:12)
#3      BallisticScrollActivity._tick (package:flutter/src/widgets/scroll_activity.dart:585:10)
#4      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:161:19)
#5      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:865:5)
#6      Ticker._tick (package:flutter/src/scheduler/ticker.dart:258:12)
#7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#8      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1233:11)
#9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#10     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1231:17)
#11     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1148:5)
#12     _invoke1 (dart:ui/hooks.dart:328:13)
#13     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:361:5)
#14     _beginFrame (dart:ui/hooks.dart:272:31)
(elided 2 frames from class _AssertionError)

The AnimationController notifying listeners was: AnimationController#3e161(▶ 4.964; for _NestedOuterBallisticScrollActivity)
════════════════════════════════════════════════════════════════════════════════
Restarted application in 378ms.
```

频繁下拉刷新，偶然会出现这个稳定，出现多次了

flutter doctor 输出：

```
[✓] Flutter (Channel stable, 3.19.0, on macOS 14.0 23A344 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.88.1)
[✓] Connected device (4 available)
[✓] Network resources
```

在 iOS 17.0、iPhone 15 的模拟器上可复现

**Comment by xuelongqy** [comment]
除了报错，暂没有其他影响。这个问题目前解决不了，之前也有很多人提过，所以关闭了
